<?php

/*
 *
 *    _______                    _
 *   |__   __|                  (_)
 *      | |_   _ _ __ __ _ _ __  _  ___
 *      | | | | | '__/ _` | '_ \| |/ __|
 *      | | |_| | | | (_| | | | | | (__
 *      |_|\__,_|_|  \__,_|_| |_|_|\___|
 *
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author TuranicTeam
 * @link https://github.com/TuranicTeam/Turanic
 *
 */

declare(strict_types=1);

namespace pocketmine\item;

use pocketmine\block\Anvil;
use pocketmine\block\Fence;
use pocketmine\block\Planks;
use pocketmine\block\CobblestoneWall;
use pocketmine\item\enchantment\Enchantment;

class CreativeItems {

    const ITEMS = [
        // planks
        ["id" => Item::WOODEN_PLANK],
        ["id" => Item::WOODEN_PLANK, "meta" => Planks::SPRUCE],
        ["id" => Item::WOODEN_PLANK, "meta" => Planks::BIRCH],
        ["id" => Item::WOODEN_PLANK, "meta" => Planks::JUNGLE],
        ["id" => Item::WOODEN_PLANK, "meta" => Planks::ACACIA],
        ["id" => Item::WOODEN_PLANK, "meta" => Planks::DARK_OAK],
        // cobblestone walls
        ["id" => Item::COBBLESTONE_WALL],
        ["id" => Item::COBBLESTONE_WALL, "meta" => CobblestoneWall::MOSSY_WALL],
        // fence
        ["id" => Item::FENCE],
        ["id" => Item::FENCE, "meta" => Fence::FENCE_SPRUCE],
        ["id" => Item::FENCE, "meta" => Fence::FENCE_BIRCH],
        ["id" => Item::FENCE, "meta" => Fence::FENCE_JUNGLE],
        ["id" => Item::FENCE, "meta" => Fence::FENCE_ACACIA],
        ["id" => Item::FENCE, "meta" => Fence::FENCE_DARKOAK],
        // fence gates
        ["id" => Item::NETHER_BRICK_FENCE],
        ["id" => Item::FENCE_GATE],
        ["id" => Item::SPRUCE_FENCE_GATE],
        ["id" => Item::BIRCH_FENCE_GATE],
        ["id" => Item::JUNGLE_FENCE_GATE],
        ["id" => Item::ACACIA_FENCE_GATE],
        ["id" => Item::FENCE_GATE_DARK_OAK],
        // stairs
        ["id" => Item::COBBLESTONE_STAIRS],
        ["id" => Item::OAK_WOOD_STAIRS],
        ["id" => Item::SPRUCE_WOOD_STAIRS],
        ["id" => Item::BIRCH_WOOD_STAIRS],
        ["id" => Item::JUNGLE_WOOD_STAIRS],
        ["id" => Item::ACACIA_WOODEN_STAIRS],
        ["id" => Item::DARK_OAK_STAIRS],
        ["id" => Item::BRICK_STAIRS],
        ["id" => Item::STONE_BRICK_STAIRS],
        ["id" => Item::NETHER_BRICK_STAIRS],
        ["id" => Item::SANDSTONE_STAIRS],
        ["id" => Item::RED_SANDSTONE_STAIRS],
        ["id" => Item::QUARTZ_STAIRS],
        ["id" => Item::PURPUR_STAIRS],
        // doors
        ["id" => Item::OAK_DOOR],
        ["id" => Item::SPRUCE_DOOR],
        ["id" => Item::BIRCH_DOOR],
        ["id" => Item::JUNGLE_DOOR],
        ["id" => Item::ACACIA_DOOR],
        ["id" => Item::DARK_OAK_DOOR],
        ["id" => Item::IRON_DOOR],
        // trapdoors
        ["id" => Item::WOODEN_TRAPDOOR],
        ["id" => Item::IRON_TRAPDOOR],

        ["id" => Item::IRON_BARS],
        // glass
        ["id" => Item::GLASS],
        ["id" => Item::STAINED_GLASS],
        ["id" => Item::STAINED_GLASS, "meta" => 8],
        ["id" => Item::STAINED_GLASS, "meta" => 7],
        ["id" => Item::STAINED_GLASS, "meta" => 15],
        ["id" => Item::STAINED_GLASS, "meta" => 12],
        ["id" => Item::STAINED_GLASS, "meta" => 14],
        ["id" => Item::STAINED_GLASS, "meta" => 1],
        ["id" => Item::STAINED_GLASS, "meta" => 4],
        ["id" => Item::STAINED_GLASS, "meta" => 5],
        ["id" => Item::STAINED_GLASS, "meta" => 13],
        ["id" => Item::STAINED_GLASS, "meta" => 9],
        ["id" => Item::STAINED_GLASS, "meta" => 3],
        ["id" => Item::STAINED_GLASS, "meta" => 11],
        ["id" => Item::STAINED_GLASS, "meta" => 10],
        ["id" => Item::STAINED_GLASS, "meta" => 2],
        ["id" => Item::STAINED_GLASS, "meta" => 6],
        // glass pane
        ["id" => Item::GLASS_PANE],
        ["id" => Item::STAINED_GLASS_PANEL],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 8],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 7],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 15],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 12],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 14],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 1],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 4],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 5],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 13],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 9],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 3],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 11],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 10],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 2],
        ["id" => Item::STAINED_GLASS_PANEL, "meta" => 6],

        ["id" => Item::LADDER],
        // slabs
        ["id" => Item::STONE_SLAB],
        ["id" => Item::SLAB, "meta" => 3],
        ["id" => Item::WOOD_SLAB, "meta" => 0],
        ["id" => Item::WOOD_SLAB, "meta" => 1],
        ["id" => Item::WOOD_SLAB, "meta" => 2],
        ["id" => Item::WOOD_SLAB, "meta" => 3],
        ["id" => Item::WOOD_SLAB, "meta" => 4],
        ["id" => Item::WOOD_SLAB, "meta" => 5],
        ["id" => Item::SLAB, "meta" => 4],
        ["id" => Item::SLAB, "meta" => 5],
        ["id" => Item::SLAB, "meta" => 7],
        ["id" => Item::SLAB, "meta" => 1],
        ["id" => Item::RED_SANDSTONE_SLAB],
        ["id" => Item::SLAB, "meta" => 6],
        ["id" => Item::RED_SANDSTONE_SLAB, "meta" => 1], // purpur stairs
        // bricks
        ["id" => Item::BRICKS],
        ["id" => Item::STONE_BRICKS],
        ["id" => Item::STONE_BRICKS, "meta" => 1],
        ["id" => Item::STONE_BRICKS, "meta" => 2],
        ["id" => Item::STONE_BRICKS, "meta" => 3],
        ["id" => Item::END_STONE_BRICKS],

        ["id" => Item::PRISMARINE, "meta" => 2],

        ["id" => Item::COBBLESTONE],
        ["id" => Item::MOSSY_STONE],
        // sandstone
        ["id" => Item::SANDSTONE],
        ["id" => Item::SANDSTONE, "meta" => 1],
        ["id" => Item::SANDSTONE, "meta" => 2],
        ["id" => Item::RED_SANDSTONE],
        ["id" => Item::RED_SANDSTONE, "meta" => 1],
        ["id" => Item::RED_SANDSTONE, "meta" => 2],

        ["id" => Item::COAL_BLOCK],
        ["id" => Item::GOLD_BLOCK],
        ["id" => Item::IRON_BLOCK],
        ["id" => Item::EMERALD_BLOCK],
        ["id" => Item::DIAMOND_BLOCK],
        ["id" => Item::LAPIS_BLOCK],
        // quartz
        ["id" => Item::QUARTZ_BLOCK],
        ["id" => Item::QUARTZ_BLOCK, "meta" => 2],
        ["id" => Item::QUARTZ_BLOCK, "meta" => 1],

        ["id" => Item::PRISMARINE],
        ["id" => Item::PRISMARINE, "meta" => 1],

        ["id" => Item::SLIME_BLOCK],
        ["id" => Item::HAY_BALE],
        ["id" => Item::BONE_BLOCK],
        // NETHER
        ["id" => Item::NETHER_WART_BLOCK],
        ["id" => Item::NETHER_BRICK],
        ["id" => Item::RED_NETHER_BRICK],
        // wool
        ["id" => Item::WOOL],
        ["id" => Item::WOOL, "meta" => 8],
        ["id" => Item::WOOL, "meta" => 7],
        ["id" => Item::WOOL, "meta" => 15],
        ["id" => Item::WOOL, "meta" => 12],
        ["id" => Item::WOOL, "meta" => 14],
        ["id" => Item::WOOL, "meta" => 1],
        ["id" => Item::WOOL, "meta" => 4],
        ["id" => Item::WOOL, "meta" => 5],
        ["id" => Item::WOOL, "meta" => 13],
        ["id" => Item::WOOL, "meta" => 9],
        ["id" => Item::WOOL, "meta" => 3],
        ["id" => Item::WOOL, "meta" => 11],
        ["id" => Item::WOOL, "meta" => 10],
        ["id" => Item::WOOL, "meta" => 2],
        ["id" => Item::WOOL, "meta" => 6],
        // carpet
        ["id" => Item::CARPET],
        ["id" => Item::CARPET, "meta" => 8],
        ["id" => Item::CARPET, "meta" => 7],
        ["id" => Item::CARPET, "meta" => 15],
        ["id" => Item::CARPET, "meta" => 12],
        ["id" => Item::CARPET, "meta" => 14],
        ["id" => Item::CARPET, "meta" => 1],
        ["id" => Item::CARPET, "meta" => 4],
        ["id" => Item::CARPET, "meta" => 5],
        ["id" => Item::CARPET, "meta" => 13],
        ["id" => Item::CARPET, "meta" => 9],
        ["id" => Item::CARPET, "meta" => 3],
        ["id" => Item::CARPET, "meta" => 11],
        ["id" => Item::CARPET, "meta" => 10],
        ["id" => Item::CARPET, "meta" => 2],
        ["id" => Item::CARPET, "meta" => 6],
        // concrete powders
        ["id" => Item::CONCRETE_POWDER],
        ["id" => Item::CONCRETE_POWDER, "meta" => 8],
        ["id" => Item::CONCRETE_POWDER, "meta" => 7],
        ["id" => Item::CONCRETE_POWDER, "meta" => 15],
        ["id" => Item::CONCRETE_POWDER, "meta" => 12],
        ["id" => Item::CONCRETE_POWDER, "meta" => 14],
        ["id" => Item::CONCRETE_POWDER, "meta" => 1],
        ["id" => Item::CONCRETE_POWDER, "meta" => 4],
        ["id" => Item::CONCRETE_POWDER, "meta" => 5],
        ["id" => Item::CONCRETE_POWDER, "meta" => 13],
        ["id" => Item::CONCRETE_POWDER, "meta" => 9],
        ["id" => Item::CONCRETE_POWDER, "meta" => 3],
        ["id" => Item::CONCRETE_POWDER, "meta" => 11],
        ["id" => Item::CONCRETE_POWDER, "meta" => 10],
        ["id" => Item::CONCRETE_POWDER, "meta" => 2],
        ["id" => Item::CONCRETE_POWDER, "meta" => 6],
        // concrete
        ["id" => Item::CONCRETE],
        ["id" => Item::CONCRETE, "meta" => 8],
        ["id" => Item::CONCRETE, "meta" => 7],
        ["id" => Item::CONCRETE, "meta" => 15],
        ["id" => Item::CONCRETE, "meta" => 12],
        ["id" => Item::CONCRETE, "meta" => 14],
        ["id" => Item::CONCRETE, "meta" => 1],
        ["id" => Item::CONCRETE, "meta" => 4],
        ["id" => Item::CONCRETE, "meta" => 5],
        ["id" => Item::CONCRETE, "meta" => 13],
        ["id" => Item::CONCRETE, "meta" => 9],
        ["id" => Item::CONCRETE, "meta" => 3],
        ["id" => Item::CONCRETE, "meta" => 11],
        ["id" => Item::CONCRETE, "meta" => 10],
        ["id" => Item::CONCRETE, "meta" => 2],
        ["id" => Item::CONCRETE, "meta" => 6],
        // clay
        ["id" => Item::CLAY_BLOCK],
        ["id" => Item::HARDENED_CLAY],
        ["id" => Item::STAINED_CLAY],
        ["id" => Item::STAINED_CLAY, "meta" => 8],
        ["id" => Item::STAINED_CLAY, "meta" => 7],
        ["id" => Item::STAINED_CLAY, "meta" => 15],
        ["id" => Item::STAINED_CLAY, "meta" => 12],
        ["id" => Item::STAINED_CLAY, "meta" => 14],
        ["id" => Item::STAINED_CLAY, "meta" => 1],
        ["id" => Item::STAINED_CLAY, "meta" => 4],
        ["id" => Item::STAINED_CLAY, "meta" => 5],
        ["id" => Item::STAINED_CLAY, "meta" => 13],
        ["id" => Item::STAINED_CLAY, "meta" => 9],
        ["id" => Item::STAINED_CLAY, "meta" => 3],
        ["id" => Item::STAINED_CLAY, "meta" => 11],
        ["id" => Item::STAINED_CLAY, "meta" => 10],
        ["id" => Item::STAINED_CLAY, "meta" => 2],
        ["id" => Item::STAINED_CLAY, "meta" => 6],
        // glazed terracotta
        ["id" => Item::WHITE_GLAZED_TERRACOTTA],
        ["id" => Item::SILVER_GLAZED_TERRACOTTA],
        ["id" => Item::GRAY_GLAZED_TERRACOTTA],
        ["id" => Item::BLACK_GLAZED_TERRACOTTA],
        ["id" => Item::BROWN_GLAZED_TERRACOTTA],
        ["id" => Item::RED_GLAZED_TERRACOTTA],
        ["id" => Item::ORANGE_GLAZED_TERRACOTTA],
        ["id" => Item::YELLOW_GLAZED_TERRACOTTA],
        ["id" => Item::LIME_GLAZED_TERRACOTTA],
        ["id" => Item::GREEN_GLAZED_TERRACOTTA],
        ["id" => Item::CYAN_GLAZED_TERRACOTTA],
        ["id" => Item::LIGHT_BLUE_GLAZED_TERRACOTTA],
        ["id" => Item::BLUE_GLAZED_TERRACOTTA],
        ["id" => Item::PURPLE_GLAZED_TERRACOTTA],
        ["id" => Item::MAGENTA_GLAZED_TERRACOTTA],
        ["id" => Item::PINK_GLAZED_TERRACOTTA],
        // purpur
        ["id" => Item::PURPUR],
        ["id" => Item::PURPUR, "meta" => 2],
        // dirt
        ["id" => Item::DIRT],
        ["id" => Item::DIRT, "meta" => 1],
        ["id" => Item::GRASS],
        ["id" => Item::PODZOL],
        ["id" => Item::MYCELIUM],

        ["id" => Item::STONE],
        // ore
        ["id" => Item::IRON_ORE],
        ["id" => Item::GOLD_ORE],
        ["id" => Item::DIAMOND_ORE],
        ["id" => Item::LAPIS_ORE],
        ["id" => Item::REDSTONE_ORE],
        ["id" => Item::COAL_ORE],
        ["id" => Item::EMERALD_ORE],
        ["id" => Item::NETHER_QUARTZ_ORE],
        // stone
        ["id" => Item::GRAVEL],
        ["id" => Item::STONE, "meta" => 1],
        ["id" => Item::STONE, "meta" => 3],
        ["id" => Item::STONE, "meta" => 5],
        ["id" => Item::STONE, "meta" => 2],
        ["id" => Item::STONE, "meta" => 4],
        ["id" => Item::STONE, "meta" => 6],
        // sand
        ["id" => Item::SAND],
        ["id" => Item::SAND, "meta" => 1],

        ["id" => Item::CACTUS],
        // log
        ["id" => Item::LOG],
        ["id" => Item::LOG, "meta" => 1],
        ["id" => Item::LOG, "meta" => 2],
        ["id" => Item::LOG, "meta" => 3],
        ["id" => Item::LOG2],
        ["id" => Item::LOG2, "meta" => 1],
        // leaves
        ["id" => Item::LEAVES],
        ["id" => Item::LEAVES, "meta" => 1],
        ["id" => Item::LEAVES, "meta" => 2],
        ["id" => Item::LEAVES, "meta" => 3],
        ["id" => Item::LEAVES2],
        ["id" => Item::LEAVES2, "meta" => 1],
        // sapling
        ["id" => Item::SAPLING],
        ["id" => Item::SAPLING, "meta" => 1],
        ["id" => Item::SAPLING, "meta" => 2],
        ["id" => Item::SAPLING, "meta" => 3],
        ["id" => Item::SAPLING, "meta" => 4],
        ["id" => Item::SAPLING, "meta" => 5],
        // seeds
        ["id" => Item::WHEAT_SEEDS],
        ["id" => Item::PUMPKIN_SEEDS],
        ["id" => Item::MELON_SEEDS],
        ["id" => Item::BEETROOT_SEED],

        ["id" => Item::WHEAT],
        ["id" => Item::BEETROOT],
        ["id" => Item::POTATO],
        ["id" => Item::POISONOUS_POTATO],
        ["id" => Item::CARROT],
        ["id" => Item::GOLDEN_CARROT],
        ["id" => Item::APPLE],
        ["id" => Item::GOLDEN_APPLE],
        ["id" => Item::ENCHANTED_GOLDEN_APPLE],
        ["id" => Item::MELON_BLOCK],
        ["id" => Item::MELON],
        ["id" => Item::GLISTERING_MELON],
        ["id" => Item::PUMPKIN],
        ["id" => Item::LIT_PUMPKIN],
        // plants
        ["id" => Item::TALL_GRASS, "meta" => 2],
        ["id" => Item::DOUBLE_PLANT, "meta" => 3],
        ["id" => Item::TALL_GRASS, "meta" => 1],
        ["id" => Item::DOUBLE_PLANT, "meta" => 2],
        ["id" => Item::DANDELION],
        ["id" => Item::POPPY],
        ["id" => Item::POPPY, "meta" => 1],
        ["id" => Item::POPPY, "meta" => 2],
        ["id" => Item::POPPY, "meta" => 3],
        ["id" => Item::POPPY, "meta" => 4],
        ["id" => Item::POPPY, "meta" => 5],
        ["id" => Item::POPPY, "meta" => 6],
        ["id" => Item::POPPY, "meta" => 7],
        ["id" => Item::POPPY, "meta" => 8],
        ["id" => Item::DOUBLE_PLANT],
        ["id" => Item::DOUBLE_PLANT, "meta" => 1],
        ["id" => Item::DOUBLE_PLANT, "meta" => 4],
        ["id" => Item::DOUBLE_PLANT, "meta" => 5],
        // dye
        ["id" => Item::DYE, "meta" => 7],
        ["id" => Item::DYE, "meta" => 8],
        ["id" => Item::DYE],
        ["id" => Item::DYE, "meta" => 1],
        ["id" => Item::DYE, "meta" => 14],
        ["id" => Item::DYE, "meta" => 11],
        ["id" => Item::DYE, "meta" => 10],
        ["id" => Item::DYE, "meta" => 2],
        ["id" => Item::DYE, "meta" => 6],
        ["id" => Item::DYE, "meta" => 12],
        ["id" => Item::DYE, "meta" => 4],
        ["id" => Item::DYE, "meta" => 5],
        ["id" => Item::DYE, "meta" => 13],
        ["id" => Item::DYE, "meta" => 9],
        ["id" => Item::DYE, "meta" => 15],
        ["id" => Item::DYE, "meta" => 3],

        ["id" => Item::VINES],
        ["id" => Item::LILY_PAD],
        ["id" => Item::DEAD_BUSH],
        ["id" => Item::SNOW_BLOCK],
        ["id" => Item::ICE],
        ["id" => Item::PACKED_ICE],
        ["id" => Item::SNOW],

        ["id" => Item::RAW_CHICKEN],
        ["id" => Item::RAW_PORKCHOP],
        ["id" => Item::RAW_BEEF],
        ["id" => Item::RAW_MUTTON],
        ["id" => Item::RAW_RABBIT],
        ["id" => Item::RAW_FISH],
        ["id" => Item::RAW_SALMON],
        ["id" => Item::CLOWN_FISH],
        ["id" => Item::PUFFER_FISH],

        ["id" => Item::BROWN_MUSHROOM],
        ["id" => Item::RED_MUSHROOM],
        ["id" => Item::BROWN_MUSHROOM_BLOCK, "meta" => 14],
        ["id" => Item::RED_MUSHROOM_BLOCK, "meta" => 14],
        ["id" => Item::RED_MUSHROOM_BLOCK],

        ["id" => Item::EGG],
        ["id" => Item::SUGAR_CANE],
        ["id" => Item::SUGAR],
        ["id" => Item::ROTTEN_FLESH],
        ["id" => Item::BONE],
        ["id" => Item::COBWEB],
        ["id" => Item::SPIDER_EYE],
        // monster egg block
        ["id" => Item::MONSTER_EGG_BLOCK],
        ["id" => Item::MONSTER_EGG_BLOCK, "meta" => 1],
        ["id" => Item::MONSTER_EGG_BLOCK, "meta" => 2],
        ["id" => Item::MONSTER_EGG_BLOCK, "meta" => 3],
        ["id" => Item::MONSTER_EGG_BLOCK, "meta" => 4],
        ["id" => Item::MONSTER_EGG_BLOCK, "meta" => 5],

        ["id" => Item::DRAGON_EGG],
        // spawn eggs
        ["id" => Item::SPAWN_EGG, "meta" => 10],
        ["id" => Item::SPAWN_EGG, "meta" => 11],
        ["id" => Item::SPAWN_EGG, "meta" => 12],
        ["id" => Item::SPAWN_EGG, "meta" => 13],
        ["id" => Item::SPAWN_EGG, "meta" => 14],
        ["id" => Item::SPAWN_EGG, "meta" => 28],
        ["id" => Item::SPAWN_EGG, "meta" => 22],
        ["id" => Item::SPAWN_EGG, "meta" => 16],
        ["id" => Item::SPAWN_EGG, "meta" => 19],
        ["id" => Item::SPAWN_EGG, "meta" => 30],
        ["id" => Item::SPAWN_EGG, "meta" => 18],
        ["id" => Item::SPAWN_EGG, "meta" => 29],
        ["id" => Item::SPAWN_EGG, "meta" => 23],
        ["id" => Item::SPAWN_EGG, "meta" => 24],
        ["id" => Item::SPAWN_EGG, "meta" => 25],
        ["id" => Item::SPAWN_EGG, "meta" => 26],
        ["id" => Item::SPAWN_EGG, "meta" => 27],
        ["id" => Item::SPAWN_EGG, "meta" => 33],
        ["id" => Item::SPAWN_EGG, "meta" => 38],
        ["id" => Item::SPAWN_EGG, "meta" => 39],
        ["id" => Item::SPAWN_EGG, "meta" => 34],
        ["id" => Item::SPAWN_EGG, "meta" => 48],
        ["id" => Item::SPAWN_EGG, "meta" => 46],
        ["id" => Item::SPAWN_EGG, "meta" => 37],
        ["id" => Item::SPAWN_EGG, "meta" => 35],
        ["id" => Item::SPAWN_EGG, "meta" => 32],
        ["id" => Item::SPAWN_EGG, "meta" => 36],
        ["id" => Item::SPAWN_EGG, "meta" => 47],
        ["id" => Item::SPAWN_EGG, "meta" => 17],
        ["id" => Item::SPAWN_EGG, "meta" => 40],
        ["id" => Item::SPAWN_EGG, "meta" => 45],
        ["id" => Item::SPAWN_EGG, "meta" => 49],
        ["id" => Item::SPAWN_EGG, "meta" => 50],
        ["id" => Item::SPAWN_EGG, "meta" => 48],
        ["id" => Item::SPAWN_EGG, "meta" => 42],
        ["id" => Item::SPAWN_EGG, "meta" => 41],
        ["id" => Item::SPAWN_EGG, "meta" => 43],
        ["id" => Item::SPAWN_EGG, "meta" => 54],
        ["id" => Item::SPAWN_EGG, "meta" => 57],
        ["id" => Item::SPAWN_EGG, "meta" => 104],
        ["id" => Item::SPAWN_EGG, "meta" => 105],
        ["id" => Item::SPAWN_EGG, "meta" => 15],
        ["id" => Item::SPAWN_EGG, "meta" => 44],

        ["id" => Item::OBSIDIAN],
        ["id" => Item::BEDROCK],
        ["id" => Item::SOUL_SAND],
        ["id" => Item::NETHERRACK],
        ["id" => Item::MAGMA],
        ["id" => Item::NETHER_WART],
        ["id" => Item::END_STONE],
        // chorus
        ["id" => Item::CHORUS_FLOWER],
        ["id" => Item::CHORUS_PLANT],
        ["id" => Item::CHORUS_FRUIT],
        ["id" => Item::POPPED_CHORUS_FRUIT],
        // sponge
        ["id" => Item::SPONGE],
        ["id" => Item::SPONGE, "meta" => 1],
        // helmet
        ["id" => Item::LEATHER_CAP],
        ["id" => Item::CHAIN_HELMET],
        ["id" => Item::IRON_HELMET],
        ["id" => Item::GOLD_HELMET],
        ["id" => Item::DIAMOND_HELMET],
        // chestplate
        ["id" => Item::LEATHER_TUNIC],
        ["id" => Item::CHAIN_CHESTPLATE],
        ["id" => Item::IRON_CHESTPLATE],
        ["id" => Item::GOLD_CHESTPLATE],
        ["id" => Item::DIAMOND_CHESTPLATE],
        // legging
        ["id" => Item::LEATHER_PANTS],
        ["id" => Item::CHAIN_LEGGINGS],
        ["id" => Item::IRON_LEGGINGS],
        ["id" => Item::GOLD_LEGGINGS],
        ["id" => Item::DIAMOND_LEGGINGS],
        // boots
        ["id" => Item::LEATHER_BOOTS],
        ["id" => Item::CHAIN_BOOTS],
        ["id" => Item::IRON_BOOTS],
        ["id" => Item::GOLD_BOOTS],
        ["id" => Item::DIAMOND_BOOTS],
        // sword
        ["id" => Item::WOODEN_SWORD],
        ["id" => Item::STONE_SWORD],
        ["id" => Item::IRON_SWORD],
        ["id" => Item::GOLD_SWORD],
        ["id" => Item::DIAMOND_SWORD],
        // axe
        ["id" => Item::WOODEN_AXE],
        ["id" => Item::STONE_AXE],
        ["id" => Item::IRON_AXE],
        ["id" => Item::GOLD_AXE],
        ["id" => Item::DIAMOND_AXE],
        // pickaxe
        ["id" => Item::WOODEN_PICKAXE],
        ["id" => Item::STONE_PICKAXE],
        ["id" => Item::IRON_PICKAXE],
        ["id" => Item::GOLD_PICKAXE],
        ["id" => Item::DIAMOND_PICKAXE],
        // shovel
        ["id" => Item::WOODEN_SHOVEL],
        ["id" => Item::STONE_SHOVEL],
        ["id" => Item::IRON_SHOVEL],
        ["id" => Item::GOLD_SHOVEL],
        ["id" => Item::DIAMOND_SHOVEL],
        // hoe
        ["id" => Item::WOODEN_HOE],
        ["id" => Item::STONE_HOE],
        ["id" => Item::IRON_HOE],
        ["id" => Item::GOLD_HOE],
        ["id" => Item::DIAMOND_HOE],

        ["id" => Item::BOW],

        // arrow
        ["id" => Item::ARROW],
        ["id" => Item::ARROW, "meta" => 6], // night visibiity
        ["id" => Item::ARROW, "meta" => 7],
        ["id" => Item::ARROW, "meta" => 8], // invisibility
        ["id" => Item::ARROW, "meta" => 9],
        ["id" => Item::ARROW, "meta" => 10], // leaping
        ["id" => Item::ARROW, "meta" => 11],
        ["id" => Item::ARROW, "meta" => 12],
        ["id" => Item::ARROW, "meta" => 13], // fire resistance
        ["id" => Item::ARROW, "meta" => 14],
        ["id" => Item::ARROW, "meta" => 15], // swiftness
        ["id" => Item::ARROW, "meta" => 16],
        ["id" => Item::ARROW, "meta" => 17],
        ["id" => Item::ARROW, "meta" => 18], // slowness
        ["id" => Item::ARROW, "meta" => 19],
        ["id" => Item::ARROW, "meta" => 20], // water breathing
        ["id" => Item::ARROW, "meta" => 21],
        ["id" => Item::ARROW, "meta" => 22], // healing
        ["id" => Item::ARROW, "meta" => 23],
        ["id" => Item::ARROW, "meta" => 24], // harming
        ["id" => Item::ARROW, "meta" => 25],
        ["id" => Item::ARROW, "meta" => 26], // poison
        ["id" => Item::ARROW, "meta" => 27],
        ["id" => Item::ARROW, "meta" => 28],
        ["id" => Item::ARROW, "meta" => 29], // regeneration
        ["id" => Item::ARROW, "meta" => 30],
        ["id" => Item::ARROW, "meta" => 31],
        ["id" => Item::ARROW, "meta" => 32], // strength
        ["id" => Item::ARROW, "meta" => 33],
        ["id" => Item::ARROW, "meta" => 34],
        ["id" => Item::ARROW, "meta" => 35], // weakness
        ["id" => Item::ARROW, "meta" => 36],
        ["id" => Item::ARROW, "meta" => 37], // decay (wither)

        ["id" => Item::COOKED_CHICKEN],
        ["id" => Item::COOKED_PORKCHOP],
        ["id" => Item::STEAK],
        ["id" => Item::COOKED_MUTTON],
        ["id" => Item::COOKED_RABBIT],
        ["id" => Item::COOKED_FISH],
        ["id" => Item::COOKED_SALMON],
        ["id" => Item::BREAD],
        ["id" => Item::MUSHROOM_STEW],
        ["id" => Item::BEETROOT_SOUP],
        ["id" => Item::RABBIT_STEW],
        ["id" => Item::BAKED_POTATOES],
        ["id" => Item::COOKIE],
        ["id" => Item::PUMPKIN_PIE],
        ["id" => Item::CAKE],
        // bucket
        ["id" => Item::BUCKET],
        ["id" => Item::BUCKET, "meta" => Bucket::TYPE_MILK],
        ["id" => Item::BUCKET, "meta" => Bucket::TYPE_WATER],
        ["id" => Item::BUCKET, "meta" => Bucket::TYPE_LAVA],

        ["id" => Item::FISHING_ROD],
        ["id" => Item::CARROT_ON_A_STICK],
        ["id" => Item::SNOWBALL],
        ["id" => Item::SHEARS],
        ["id" => Item::FLINT_AND_STEEL],
        ["id" => Item::LEAD],
        ["id" => Item::CLOCK],
        ["id" => Item::COMPASS],
        ["id" => Item::EMPTY_MAP],
        ["id" => Item::EMPTY_MAP, "meta" => 2],
        ["id" => Item::SADDLE],
        // horse armor
        ["id" => Item::LEATHER_HORSE_ARMOR],
        ["id" => Item::IRON_HORSE_ARMOR],
        ["id" => Item::GOLD_HORSE_ARMOR],
        ["id" => Item::DIAMOND_HORSE_ARMOR],

        ["id" => Item::ELYTRA],
        ["id" => Item::TOTEM],
        ["id" => Item::GLASS_BOTTLE],
        ["id" => Item::BOTTLE_O_ENCHANTING],
        ["id" => Item::POTION],
        ["id" => Item::POTION, "meta" => 1],
        ["id" => Item::POTION, "meta" => 2],
        ["id" => Item::POTION, "meta" => 3],
        ["id" => Item::POTION, "meta" => 4],
        ["id" => Item::POTION, "meta" => 5],
        ["id" => Item::POTION, "meta" => 6],
        ["id" => Item::POTION, "meta" => 7],
        ["id" => Item::POTION, "meta" => 8],
        ["id" => Item::POTION, "meta" => 9],
        ["id" => Item::POTION, "meta" => 10],
        ["id" => Item::POTION, "meta" => 11],
        ["id" => Item::POTION, "meta" => 12],
        ["id" => Item::POTION, "meta" => 13],
        ["id" => Item::POTION, "meta" => 14],
        ["id" => Item::POTION, "meta" => 15],
        ["id" => Item::POTION, "meta" => 16],
        ["id" => Item::POTION, "meta" => 17],
        ["id" => Item::POTION, "meta" => 18],
        ["id" => Item::POTION, "meta" => 19],
        ["id" => Item::POTION, "meta" => 20],
        ["id" => Item::POTION, "meta" => 21],
        ["id" => Item::POTION, "meta" => 22],
        ["id" => Item::POTION, "meta" => 23],
        ["id" => Item::POTION, "meta" => 24],
        ["id" => Item::POTION, "meta" => 25],
        ["id" => Item::POTION, "meta" => 26],
        ["id" => Item::POTION, "meta" => 27],
        ["id" => Item::POTION, "meta" => 28],
        ["id" => Item::POTION, "meta" => 29],
        ["id" => Item::POTION, "meta" => 30],
        ["id" => Item::POTION, "meta" => 31],
        ["id" => Item::POTION, "meta" => 32],
        ["id" => Item::POTION, "meta" => 33],
        ["id" => Item::POTION, "meta" => 34],
        ["id" => Item::POTION, "meta" => 35],
        ["id" => Item::POTION, "meta" => 36],

        ["id" => Item::SPLASH_POTION],
        ["id" => Item::SPLASH_POTION, "meta" => 1],
        ["id" => Item::SPLASH_POTION, "meta" => 2],
        ["id" => Item::SPLASH_POTION, "meta" => 3],
        ["id" => Item::SPLASH_POTION, "meta" => 4],
        ["id" => Item::SPLASH_POTION, "meta" => 5],
        ["id" => Item::SPLASH_POTION, "meta" => 6],
        ["id" => Item::SPLASH_POTION, "meta" => 7],
        ["id" => Item::SPLASH_POTION, "meta" => 8],
        ["id" => Item::SPLASH_POTION, "meta" => 9],
        ["id" => Item::SPLASH_POTION, "meta" => 10],
        ["id" => Item::SPLASH_POTION, "meta" => 11],
        ["id" => Item::SPLASH_POTION, "meta" => 12],
        ["id" => Item::SPLASH_POTION, "meta" => 13],
        ["id" => Item::SPLASH_POTION, "meta" => 14],
        ["id" => Item::SPLASH_POTION, "meta" => 15],
        ["id" => Item::SPLASH_POTION, "meta" => 16],
        ["id" => Item::SPLASH_POTION, "meta" => 17],
        ["id" => Item::SPLASH_POTION, "meta" => 18],
        ["id" => Item::SPLASH_POTION, "meta" => 19],
        ["id" => Item::SPLASH_POTION, "meta" => 20],
        ["id" => Item::SPLASH_POTION, "meta" => 21],
        ["id" => Item::SPLASH_POTION, "meta" => 22],
        ["id" => Item::SPLASH_POTION, "meta" => 23],
        ["id" => Item::SPLASH_POTION, "meta" => 24],
        ["id" => Item::SPLASH_POTION, "meta" => 25],
        ["id" => Item::SPLASH_POTION, "meta" => 26],
        ["id" => Item::SPLASH_POTION, "meta" => 27],
        ["id" => Item::SPLASH_POTION, "meta" => 28],
        ["id" => Item::SPLASH_POTION, "meta" => 29],
        ["id" => Item::SPLASH_POTION, "meta" => 30],
        ["id" => Item::SPLASH_POTION, "meta" => 31],
        ["id" => Item::SPLASH_POTION, "meta" => 32],
        ["id" => Item::SPLASH_POTION, "meta" => 33],
        ["id" => Item::SPLASH_POTION, "meta" => 34],
        ["id" => Item::SPLASH_POTION, "meta" => 35],
        ["id" => Item::SPLASH_POTION, "meta" => 36],

        ["id" => Item::LINGERING_POTION],
        ["id" => Item::LINGERING_POTION, "meta" => 1],
        ["id" => Item::LINGERING_POTION, "meta" => 2],
        ["id" => Item::LINGERING_POTION, "meta" => 3],
        ["id" => Item::LINGERING_POTION, "meta" => 4],
        ["id" => Item::LINGERING_POTION, "meta" => 5],
        ["id" => Item::LINGERING_POTION, "meta" => 6],
        ["id" => Item::LINGERING_POTION, "meta" => 7],
        ["id" => Item::LINGERING_POTION, "meta" => 8],
        ["id" => Item::LINGERING_POTION, "meta" => 9],
        ["id" => Item::LINGERING_POTION, "meta" => 10],
        ["id" => Item::LINGERING_POTION, "meta" => 11],
        ["id" => Item::LINGERING_POTION, "meta" => 12],
        ["id" => Item::LINGERING_POTION, "meta" => 13],
        ["id" => Item::LINGERING_POTION, "meta" => 14],
        ["id" => Item::LINGERING_POTION, "meta" => 15],
        ["id" => Item::LINGERING_POTION, "meta" => 16],
        ["id" => Item::LINGERING_POTION, "meta" => 17],
        ["id" => Item::LINGERING_POTION, "meta" => 18],
        ["id" => Item::LINGERING_POTION, "meta" => 19],
        ["id" => Item::LINGERING_POTION, "meta" => 20],
        ["id" => Item::LINGERING_POTION, "meta" => 21],
        ["id" => Item::LINGERING_POTION, "meta" => 22],
        ["id" => Item::LINGERING_POTION, "meta" => 23],
        ["id" => Item::LINGERING_POTION, "meta" => 24],
        ["id" => Item::LINGERING_POTION, "meta" => 25],
        ["id" => Item::LINGERING_POTION, "meta" => 26],
        ["id" => Item::LINGERING_POTION, "meta" => 27],
        ["id" => Item::LINGERING_POTION, "meta" => 28],
        ["id" => Item::LINGERING_POTION, "meta" => 29],
        ["id" => Item::LINGERING_POTION, "meta" => 30],
        ["id" => Item::LINGERING_POTION, "meta" => 31],
        ["id" => Item::LINGERING_POTION, "meta" => 32],
        ["id" => Item::LINGERING_POTION, "meta" => 33],
        ["id" => Item::LINGERING_POTION, "meta" => 34],
        ["id" => Item::LINGERING_POTION, "meta" => 35],
        ["id" => Item::LINGERING_POTION, "meta" => 36],

        ["id" => Item::STICK],
        // bed
        ["id" => Item::BED, "meta" => Bed::WHITE_BED],
        ["id" => Item::BED, "meta" => Bed::LIGHT_GRAY_BED],
        ["id" => Item::BED, "meta" => Bed::GRAY_BED],
        ["id" => Item::BED, "meta" => Bed::BLACK_BED],
        ["id" => Item::BED, "meta" => Bed::BROWN_BED],
        ["id" => Item::BED, "meta" => Bed::RED_BED],
        ["id" => Item::BED, "meta" => Bed::ORANGE_BED],
        ["id" => Item::BED, "meta" => Bed::YELLOW_BED],
        ["id" => Item::BED, "meta" => Bed::LIME_BED],
        ["id" => Item::BED, "meta" => Bed::GREEN_BED],
        ["id" => Item::BED, "meta" => Bed::CYAN_BED],
        ["id" => Item::BED, "meta" => Bed::LIGHT_BLUE_BED],
        ["id" => Item::BED, "meta" => Bed::BLUE_BED],
        ["id" => Item::BED, "meta" => Bed::PURPLE_BED],
        ["id" => Item::BED, "meta" => Bed::MAGENTA_BED],
        ["id" => Item::BED, "meta" => Bed::PINK_BED],

        ["id" => Item::TORCH],
        ["id" => Item::WORKBENCH],
        ["id" => Item::FURNACE],
        ["id" => Item::BREWING_STAND],

        ["id" => Item::ANVIL],
        ["id" => Item::ANVIL, "meta" => Anvil::TYPE_SLIGHTLY_DAMAGED],
        ["id" => Item::ANVIL, "meta" => Anvil::TYPE_VERY_DAMAGED],

        ["id" => Item::ENCHANT_TABLE],
        ["id" => Item::BOOKSHELF],
        ["id" => Item::CAULDRON],
        ["id" => Item::CHEST],
        ["id" => Item::TRAPPED_CHEST],
        ["id" => Item::ENDER_CHEST],
        // shulker box
        ["id" => Item::SHULKER_BOX],
        ["id" => Item::SHULKER_BOX, "meta" => 8],
        ["id" => Item::SHULKER_BOX, "meta" => 7],
        ["id" => Item::SHULKER_BOX, "meta" => 15],
        ["id" => Item::SHULKER_BOX, "meta" => 12],
        ["id" => Item::SHULKER_BOX, "meta" => 14],
        ["id" => Item::SHULKER_BOX, "meta" => 1],
        ["id" => Item::SHULKER_BOX, "meta" => 4],
        ["id" => Item::SHULKER_BOX, "meta" => 5],
        ["id" => Item::SHULKER_BOX, "meta" => 13],
        ["id" => Item::SHULKER_BOX, "meta" => 9],
        ["id" => Item::SHULKER_BOX, "meta" => 3],
        ["id" => Item::SHULKER_BOX, "meta" => 11],
        ["id" => Item::SHULKER_BOX, "meta" => 10],
        ["id" => Item::SHULKER_BOX, "meta" => 2],
        ["id" => Item::SHULKER_BOX, "meta" => 6],

        ["id" => Item::ARMOR_STAND],
        // music
        ["id" => Item::NOTEBLOCK],
        ["id" => Item::JUKEBOX],
        ["id" => Item::MUSIC_DISC_13],
        ["id" => Item::MUSIC_DISC_CAT],
        ["id" => Item::MUSIC_DISC_BLOCKS],
        ["id" => Item::MUSIC_DISC_FAR],
        ["id" => Item::MUSIC_DISC_MALL],
        ["id" => Item::MUSIC_DISC_MELLOHI],
        ["id" => Item::MUSIC_DISC_STAL],
        ["id" => Item::MUSIC_DISC_STAL],
        ["id" => Item::MUSIC_DISC_STRAD],
        ["id" => Item::MUSIC_DISC_WARD],
        ["id" => Item::MUSIC_DISC_11],

        ["id" => Item::GLOWSTONE_DUST],
        ["id" => Item::GLOWSTONE],
        ["id" => Item::REDSTONE_LAMP],
        ["id" => Item::SEA_LANTERN],
        ["id" => Item::SIGN],
        ["id" => Item::PAINTING],
        ["id" => Item::ITEM_FRAME],
        ["id" => Item::FLOWER_POT],
        ["id" => Item::BOWL],
        // skull
        ["id" => Item::SKULL, "meta" => Skull::STEVE],
        ["id" => Item::SKULL, "meta" => Skull::ZOMBIE],
        ["id" => Item::SKULL, "meta" => Skull::CREEPER],
        ["id" => Item::SKULL, "meta" => Skull::DRAGON],
        ["id" => Item::SKULL, "meta" => Skull::SKELETON],
        ["id" => Item::SKULL, "meta" => Skull::WITHER_SKELETON],

        ["id" => Item::BEACON],
        ["id" => Item::STONECUTTER],
        ["id" => Item::END_PORTAL_FRAME],
        ["id" => Item::COAL],
        ["id" => Item::COAL, "meta" => 1],
        ["id" => Item::DIAMOND],
        ["id" => Item::IRON_NUGGET],
        ["id" => Item::IRON_INGOT],
        ["id" => Item::GOLDEN_NUGGET],
        ["id" => Item::GOLD_INGOT],
        ["id" => Item::EMERALD],
        ["id" => Item::QUARTZ],
        ["id" => Item::CLAY],
        ["id" => Item::BRICK],
        ["id" => Item::NETHER_BRICK],
        ["id" => Item::PRISMARINE_SHARD],
        ["id" => Item::PRISMARINE_CRYSTALS],
        ["id" => Item::STRING],
        ["id" => Item::FEATHER],
        ["id" => Item::FLINT],
        ["id" => Item::GUNPOWDER],
        ["id" => Item::LEATHER],
        ["id" => Item::RABBIT_HIDE],
        ["id" => Item::RABBIT_FOOT],
        ["id" => Item::FIRE_CHARGE],
        ["id" => Item::BLAZE_ROD],
        ["id" => Item::BLAZE_POWDER],
        ["id" => Item::MAGMA_CREAM],
        ["id" => Item::FERMENTED_SPIDER_EYE],
        ["id" => Item::DRAGONS_BREATH],
        ["id" => Item::SHULKER_SHELL],
        ["id" => Item::GHAST_TEAR],
        ["id" => Item::SLIMEBALL],
        ["id" => Item::ENDER_PEARL],
        ["id" => Item::EYE_OF_ENDER],
        ["id" => Item::NETHER_STAR],
        ["id" => Item::END_ROD],
        ["id" => Item::END_CRYSTAL],
        ["id" => Item::PAPER],
        ["id" => Item::BOOK],
        ["id" => Item::WRITABLE_BOOK],

        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PROTECTION, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PROTECTION, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PROTECTION, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PROTECTION, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FIRE_PROTECTION, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FIRE_PROTECTION, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FIRE_PROTECTION, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FIRE_PROTECTION, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FEATHER_FALLING, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FEATHER_FALLING, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FEATHER_FALLING, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FEATHER_FALLING, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BLAST_PROTECTION, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BLAST_PROTECTION, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BLAST_PROTECTION, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BLAST_PROTECTION, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PROJECTILE_PROTECTION, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PROJECTILE_PROTECTION, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PROJECTILE_PROTECTION, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PROJECTILE_PROTECTION, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::THORNS, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::THORNS, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::THORNS, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::DEPTH_STRIDER, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::DEPTH_STRIDER, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::DEPTH_STRIDER, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::DEPTH_STRIDER, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::DEPTH_STRIDER, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::DEPTH_STRIDER, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::AQUA_AFFINITY, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SHARPNESS, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SHARPNESS, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SHARPNESS, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SHARPNESS, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SHARPNESS, "lvl" => 5]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SMITE, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SMITE, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SMITE, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SMITE, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SMITE, "lvl" => 5]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BANE_OF_ARTHROPODS, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BANE_OF_ARTHROPODS, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BANE_OF_ARTHROPODS, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BANE_OF_ARTHROPODS, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::BANE_OF_ARTHROPODS, "lvl" => 5]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::KNOCKBACK, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::KNOCKBACK, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FIRE_ASPECT, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FIRE_ASPECT, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LOOTING, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LOOTING, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LOOTING, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::EFFICIENCY, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::EFFICIENCY, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::EFFICIENCY, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::EFFICIENCY, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::EFFICIENCY, "lvl" => 5]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::SILK_TOUCH, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::UNBREAKING, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::UNBREAKING, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::UNBREAKING, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FORTUNE, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FORTUNE, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::FORTUNE, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::POWER, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::POWER, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::POWER, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::POWER, "lvl" => 4]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::POWER, "lvl" => 5]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PUNCH, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PUNCH, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::PUNCH, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::INFINITY, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LUCK_OF_THE_SEA, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LUCK_OF_THE_SEA, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LUCK_OF_THE_SEA, "lvl" => 3]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LURE, "lvl" => 1]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LURE, "lvl" => 2]]],
        ["id" => Item::ENCHANTED_BOOK, "ench" => [["id" => Enchantment::LURE, "lvl" => 3]]],
        // boat
        ["id" => Item::BOAT],
        ["id" => Item::BOAT, "meta" => 1],
        ["id" => Item::BOAT, "meta" => 2],
        ["id" => Item::BOAT, "meta" => 3],
        ["id" => Item::BOAT, "meta" => 4],
        ["id" => Item::BOAT, "meta" => 5],
        // rail
        ["id" => Item::RAIL],
        ["id" => Item::POWERED_RAIL],
        ["id" => Item::DETECTOR_RAIL],
        ["id" => Item::ACTIVATOR_RAIL],
        // minecraft
        ["id" => Item::MINECART],
        ["id" => Item::MINECART_WITH_CHEST],
        ["id" => Item::MINECART_WITH_HOPPER],
        ["id" => Item::MINECART_WITH_TNT],
        // redstone
        ["id" => Item::REDSTONE_DUST],
        ["id" => Item::REDSTONE_BLOCK],
        ["id" => Item::LIT_REDSTONE_TORCH],
        ["id" => Item::LEVER],
        ["id" => Item::WOODEN_BUTTON, "meta" => 5],
        ["id" => Item::STONE_BUTTON, "meta" => 5],
        ["id" => Item::TRIPWIRE_HOOK],
        ["id" => Item::WOODEN_PRESSURE_PLATE],
        ["id" => Item::STONE_PRESSURE_PLATE],
        ["id" => Item::GOLD_PRESSURE_PLATE],
        ["id" => Item::IRON_PRESSURE_PLATE],
        ["id" => Item::OBSERVER],
        ["id" => Item::DAYLIGHT_DETECTOR],
        ["id" => Item::REPEATER],
        ["id" => Item::COMPARATOR],
        ["id" => Item::HOPPER],
        ["id" => Item::DROPPER],
        ["id" => Item::DISPENSER],
        ["id" => Item::PISTON],
        ["id" => Item::STICKY_PISTON],
        ["id" => Item::TNT],
        ["id" => Item::NAMETAG],
        // banner
        ["id" => Item::BANNER],
        ["id" => Item::BANNER, "meta" => 8],
        ["id" => Item::BANNER, "meta" => 7],
        ["id" => Item::BANNER, "meta" => 15],
        ["id" => Item::BANNER, "meta" => 12],
        ["id" => Item::BANNER, "meta" => 14],
        ["id" => Item::BANNER, "meta" => 1],
        ["id" => Item::BANNER, "meta" => 4],
        ["id" => Item::BANNER, "meta" => 5],
        ["id" => Item::BANNER, "meta" => 13],
        ["id" => Item::BANNER, "meta" => 9],
        ["id" => Item::BANNER, "meta" => 3],
        ["id" => Item::BANNER, "meta" => 11],
        ["id" => Item::BANNER, "meta" => 10],
        ["id" => Item::BANNER, "meta" => 2],
        ["id" => Item::BANNER, "meta" => 6],

        ["id" => Item::FIREWORK_STAR],

    ];
}